version: 1
formatters:
  simple:
    format: '%(asctime)s %(name)-12s %(levelname)-8s %(message)s'
  minimal:
    format: '%(levelname)-10s %(message)s'

handlers:
  console:
    level: DEBUG
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stdout

  stderr:
    level: DEBUG
    class: logging.StreamHandler
    formatter: simple
    stream: ext://sys.stderr

  logfile:
    level: DEBUG
    filename: ip2sl.log
    class: logging.FileHandler
    formatter: simple
    encoding: utf8

root:
  level: DEBUG
  handlers: [console, logfile]
