# Example config for a StarTech 8-port USB serial adapter (ICUSB232I)

serial:

  1: # port 1
    path: /dev/tty.usbserial-A501SGSU
    baud: 9600
    flow: FLOW_NONE # flowcontrol = RS232
    parity: PARITY_NO
    stop_bits: STOPBITS_1

  2:
    path: /dev/tty.usbserial-A501SGSV
    baud: 9600

  3:
    path: /dev/tty.usbserial-A501SGSW
    baud: 14400

  4:
    path: /dev/tty.usbserial-A501SGSX
    baud: 14400

  5:
    path: /dev/tty.usbserial-A501SGSY
    baud: 115200

  6:
    path: /dev/tty.usbserial-A501SGSZ
    baud: 115200

  7:
    path: /dev/tty.usbserial-A501SGT0
    baud: 115200

  8:
    path: /dev/tty.usbserial-A501SGT1
    baud: 115200